
FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

LABEL maintainer="AI <407144063@qq.com>"

# Update CA Certificates
RUN apt-get update && \
    apt-get install -y --reinstall \
        curl \
        ca-certificates && \
    apt-get clean && \
    apt-get autoremove && \
     rm -rf /var/lib/{apt,dpkg,cache,log}/ /tmp/* /var/tmp/*

# Python 3
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev && \
        apt-get clean && \
        apt-get autoremove && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# pip
RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py


# new system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ \
        libblas-dev \
        python3-tk \
        git && \
        apt-get clean && \
        apt-get autoremove && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# new python dependencies
RUN pip --no-cache-dir install -i https://pypi.tuna.tsinghua.edu.cn/simple \
    matplotlib \
    h5py \
    numpy \
    pandas \
    pillow \
    scikit-image \
    scipy \
    nose \
    sklearn \
    tensorflow-gpu


RUN pip --no-cache-dir install -i https://pypi.tuna.tsinghua.edu.cn/simple \
    jieba \
    gensim


# Keras
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git
ENV KERAS_BACKEND tensorflow

WORKDIR "/root"
CMD ["/bin/bash"]